### PR TITLE
[Proposal] Dwifft -> Differ

### PR DESCRIPTION
**Pull request by benasher44**
## Changes in this pull request

This converts us from using Dwifft to using Differ, which uses a much faster algorithm, ~similar to IGListDiff~ although it is still inferior to IGListDiff. We can switch to IGListDiff, but we can consider this an intermediate step. This should fix our immediate performance problems (both CPU and memory), and then we'll have more time to consider how we want to integrate IGListDiff and grapple with the related value -> reference type changes.

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/plangrid/ReactiveLists/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by benasher44** [comment]
The other upside to leaving Dwifft early is that Dwifft doesn't seem to be maintained, but Differ still has an active maintainer: http://github.com/tonyarnold/Differ

**Comment by PlanBot-iOS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Source code changes (in APIs or behaviors) should have an entry in CHANGELOG.md.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by benasher44** [comment]
Okay so I found this list of diff algos: https://github.com/onmyway133/blog/issue/99, which nicely highlights some of Swift diff implementations out there.

https://github.com/onmyway133/DeepDiff (from the issue author) seems to have the best combo of contributors + GH stars from that list. I'm thinking about switching to this one. It checks all of the boxes for me for a more permanent departure from Dwifft:

- Swift-native
- Actively maintained
- Paul Heckel diff algo (same as IGListKit)

I am concerned about IGListDiff introducing Obj-C cruft into ReactiveLists, and the ripple effect that might have through our codebase. But maybe others had an idea for how to guard the Obj-C dependencies from leaking outside this lib? Thoughts?

**Comment by asmallteapot** [comment]
This link seems to not be working…? https://github.com/onmyway133/blog/issue/99

DeepDiff looks very good. I particularly like that there's a clean separation between the core diffing algorithm and the  iOS-specific helpers.

My biggest worry about introducing a dependency on IGListKit has been that it, well, does the same thing we're trying to do, in another language. So this seems like a path worth pursuing.

**Comment by benasher44** [comment]
Ah whoops fixed!

I agree. I also like https://github.com/ra1028/DifferenceKit. It has fewer contributors, but:

- DifferenceKit acknowledges in the README there are issues performing batch update to table views that can cause crashes and discusses how it gets around them (DeepDiff has an open [issue that seems related and is still open](https://github.com/onmyway133/DeepDiff/issues/8).
- There are also some other [open](https://github.com/onmyway133/DeepDiff/issues/13) [issues](https://github.com/onmyway133/DeepDiff/issues/21) in DeepDiff around hashValue and equality, which look concerning. DifferenceKit's protocol (looks similar to IGListDiffable) avoids this
- DifferenceKit also looks like it has some of the extensions I would add to improve DeepDiff's nested array support.

**Comment by benasher44** [comment]
Going to give `DifferenceKit` a try. Its protocol is most similar to IGListDiffable, so it won't take us too far from that route (if decide to take it down the road).

**Comment by benasher44** [comment]
Models would need to be `IGListDiffable`, which is an Obj-C protocol. That means we'd need to introduce classes where we otherwise wouldn't.

**Comment by jessesquires** [comment]
The protocol is declared as `@protocol IGListDiffable` not `@protocol IGListDiffable <NSObject>`.
https://github.com/Instagram/IGListKit/blob/master/Source/Common/IGListDiffable.h#L14

Which *I think* bridges to `Any` now, right? (And `id<IGListDiffable>` should also bridge as `Any`)

**Comment by benasher44** [comment]
`id` params do bridge to `Any` (although `id<Protocol>` might be bridged to `Protocol`), but Obj-C protocols have to be implemented as `class` types. I made a sample app with this protocol:
```
@protocol ProtocolA

- (void)foo;

@end
```
When I try to implement this on a `struct` (named `S` in the example), I get this error in Swift:
```
Non-class type 'S' cannot conform to class protocol 'ProtocolA'
```

**Comment by benasher44** [comment]
Looks like Ryan's comment on this thread still applies: 
https://github.com/Instagram/IGListKit/issues/35#issuecomment-259730982

Looks like both Swift generics (in the case of DifferenceKit) and Obj-C compatibility (in the case of IGListKit) both force us into some kind of type erasure. We just have to decide which one we're okay with :)

**Comment by jessesquires** [comment]
Ugh, right. I remember this now.

We'd have do to a boxing/unboxing dance:
https://github.com/Instagram/IGListKit/issues/35#issuecomment-250750229

**Pull request closed without merging**
