### PR TITLE
Fix crash when diffing to/from empty/nil states to/from non-empty/nil states

### LINKED ISSUE #124: [Crash] Crash in diffing when moving to/from empty/nil states to non-empty/nil states
PlanGrid IP-3275

### PR DESCRIPTION
**Pull request by jessesquires**
Closes #124
Internal: IP-3275

### CODE REVIEW

**Comment by Hera-Plangrid** [comment]
https://plangrid.atlassian.net/browse/IP-3275

**Comment by jessesquires** [comment]
Ok. Pushed more fixes. (Tests were failing)

I can consistently crash UIKit because `Dwifft` is **not** producing correct diffs.

That's out of scope for this PR right now though. We'll have to live with it until we can switch to IGListKit.

**Comment by asmallteapot** [comment]
@jessesquires Is the crashing consistent enough that we could throw an exception from `ReactiveLists` to make its source clearer?

**Comment by jessesquires** [comment]
Follow-up at #126

**Pull request merged**
