### PR TITLE
[Docs] Initial Vision

### PR DESCRIPTION
**Pull request by Ben-G**
This is based largely on our recent lunch discussion 😉 
Wonder if I need to elaborate more for folks not familiar with React?

### CODE REVIEW

**Comment by anayini** [comment]
I think there is no need to elaborate further, especially with the link there.  Seems good - clear and concise.

**Comment by Ben-G** [comment]
Addressed your comment and merged @jessesquires!

**Comment by jessesquires** [comment]
@Ben-G -- did you forget to push? 😅 don't see any changes 😄

**Comment by Ben-G** [comment]
@jessesquires Psssst... Yes I did; and then forced push to `master` before anyone noticed - so I thought!

Obviously would have opened a new PR if this had been post initial release 😉

**Comment by jessesquires** [comment]
@Ben-G lolololololololol

**Pull request merged**
