### PR TITLE
More updates to getting started

### PR DESCRIPTION
**Pull request by anayini**
@jessesquires - Here is a quick draft of the getting started with a more simple intro.  Look it over and if this generally seems right then I'll polish it up a bit, ensure the code is valid against `dev` .

### CODE REVIEW

**Comment by Hera-Plangrid** [comment]
Mention JIRA ticket numbers in commit comments to automatically link them.

**Comment by jessesquires** [comment]
don't forget to re-gen docs before you merge 😊

**Comment by anayini** [comment]
@jessesquires - Yup will do.  I'll update to your example and do some more proofreading and testing

**Comment by PlanBot-iOS** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Docs are regenerated when creating new releases.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Docs are generated by using <a href="https://github.com/realm/jazzy">Jazzy</a>. If you want to contribute, please update the <a href="https://github.com/plangrid/ReactiveLists/tree/master/Guides">markdown guides</a> or doc comments.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Pull request merged**
