### PR TITLE
Update travis to use Xcode 9.4

### LINKED ISSUE #116: TravisCI failures
Travis appears to be [having problems building master](https://travis-ci.org/plangrid/ReactiveLists/jobs/371770354#L792):

```
❌  /Users/travis/build/plangrid/ReactiveLists/Sources/TableViewDriver.swift:113:47: value of type '[IndexPath]' has no member 'compactMap'
        let indexPathsAndViewModelsToReload = visibleIndexPaths.compactMap { indexPath in
                                              ^~~~~~~~~~~~~~~~~ ~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by jessesquires**
Closes #116

### CODE REVIEW

**Comment by asmallteapot** [comment]
Looks like code signing is failing in the test bundle for some reason??

**Comment by jessesquires** [comment]
😅 🔫

**Comment by jessesquires** [comment]
looks like travis is just shitting itself now. this should fix things. going to merge.

**Comment by anayini** [comment]
lol

**Pull request merged**
