### PR TITLE
[CI] Add Danger to CI

### PR DESCRIPTION
**Pull request by anayini**
Adds back Danger to CI

## Changes in this pull request

Issue fixed: #

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/plangrid/ReactiveLists/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anayini** [comment]
In progress as Danger is reporting that this isn't a `GitHub Actions PR` and isn't running.

**Comment by anayini** [comment]
@ronaldsmartin seems to work although the danger action only runs on `pull_request` events.  I've updated to run our check ons `push` and `pull_request`.  On `push` events the danger action is a noop

**Comment by jessesquires** [comment]
Danger should be commenting on here right? Maybe make a change that would trigger it to make sure.

**Comment by anayini** [comment]
@jessesquires yeah I really wish there was just a manual trigger UI in this thing

**Comment by jessesquires** [comment]
you can run danger locally:

https://danger.systems/guides/troubleshooting.html#i-want-to-work-locally-on-my-dangerfile

**Comment by ronaldsmartin** [comment]
Unassigned myself from this!

**Comment by jessesquires** [comment]
closing this to clean up my github PRs. 

and no one involved in this PR works at plangrid anymore. lol ✌🏼

**Pull request closed without merging**
